name: cream_of_the_crop
description: Blazingly fast image transformations for Flutter Web.
version: 0.91.1
homepage: https://rideout.studio
repository: https://github.com/mdrideout/cream_of_the_crop


environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CreamOfTheCropWeb
        fileName: cream_of_the_crop_web.dart
